spring:
  application:
    name: blog-base
  config:
    import: application-secret.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # data 초기화
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false


