spring:
  application:
    name: blog-base
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # data 초기화
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

jwt:
  issuer: jydev763@gmail.com
  secret_key: blog-base
