spring:
  application:
    name: blog-base
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

    # data 초기화
#    defer-datasource-initialization: true
